---
layout: post
title: Kscript as substitute for awk
description: "Use kscript and kotlin snippets for versioned zero-deployment tool development"
categories: [kotlin]
comments: true
---


Among other new [features](https://github.com/holgerbrandl/kscript/blob/master/NEWS.md#v13) `kscript` does now accept scriptlets as arguments which makes it also possible to use it in an awk-like fashion. For sure its scope is dffierent, but still it's interesting both to compare both side by side.


So let's get started. The most common aspect of awk which is printing lines

[Add a new column to a file](http://stackoverflow.com/questions/7551991/add-a-new-column-to-the-file)

```{r something-in-Bash, engine='bash', comment='Bash>'}
awk '{print $0, "F11"}' someFile

kscript 'lines.split().map { listOf(it[1], it[3]) }.print()' someFile
```

## Examples
Is awk really the

Where `kscript` excels is structured data. Take files for an example. Because of their structure each record may span a different number of rows in the file. Commonly `awk` solution

Dedicated tools to approach fasta-maniuplation tasks exist, but why not just using a _self-contained mini-application_ writtien in kscript.


## Performance


## Conceptual Clarity vs Convenience

One of the core motivations during the development of `kscript` is long-term stability of `kscript`lets. However, by adding a prefix header including a dependency on the [kscript support API](https://github.com/holgerbrandl/kscript-support-api) we're somehow condemend to either skip to the current version of the support api for all times, or to hope that gradual improvements do not break existing kscript solutions.

Because of that, we still consider to replace/drop the support for automatic prefixing of one-liners. The more verbose solution would be fixed even if we evolve the support API, but for sure conciseness is a lot worse. See yourself:


```
kscript 'lines.split().select(with(1..3).and(3)).print()' file.txt
```
vs.

```
kscript '//DEPS de.mpicbg.scicomp:kscript:1.2
import kscript.text.*
val lines = resolveArgFile(args)

lines split().select(with(1..3).and(3)).print()
'
```
 Readability would be even better in the latter case because it is a self-contained Kotlin.

Opinions and suggestions on this feature are welcome!


## Summary

As we have discussed above, `kscript` can be used as a drop-in replacement for awk in situations where `awk` solutions would become overly clumsy. By allowing for standard kotlin to write little pieces of shell processing logic, we can avoid installing external dedicated tools in many solutions. Although, `kscript` written in `Kotlin` are slightly more verbose than `awk` code, they are more readable and allow to express more complex data flow logic.

Whereas as table streaming is certainly possible with `kscript` and benficial in some situations, its true _true power_ is the handling of more complex data-types, such as  _json_, and _xml_, and domain specific data like _fasta_ or alignment files in bioinformatics. Because of the built-in dependency resolution in `kscript` third party libraries can be easily used in short concise mini-programs built with `kscript`.





{% include comments.html %}
